[project]
name = "workload"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Michael Legleux", email = "mlegleux@ripple.com" }
]
dependencies = [
    "xrpl-py",
    "antithesis>=0.1.17",
    "requests>=2.32.4",
    "anyio>=4.9.0",
    "ruamel-yaml>=0.18.14",
    "fastapi[standard]>=0.116.1",
    "uvicorn[standard]>=0.35.0",
    "names>=0.3.0",
    "asyncio>=4.0.0",
    "pydantic-settings>=2.11.0",
]
readme = "README.md"
requires-python = ">= 3.13"
license = { text = "MIT" }

[project.scripts]
workload = "workload.__main__:main"

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

[tool.uv_build.build.targets.sdist]
include = [
  "src/workload",
  "src/workload/templates/**",
  "pyproject.toml",
  "README.md",
]

[tool.ruff]
line-length = 120
target-version = "py313"
select = [
    "ANN201", # methods must have return types
]
exclude = [
    ".git",
]
lint.select = [
    "B",
    "E",
    "F",
    # "D",
    "Q",
]

# lint.extend-select = ["D"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
lint = [
    "ruff>=0.14.1",
]
